name: Deploy DynamoDB Table

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
      - main
    paths:
      - "templates/user-table.yml"
      - "templates/booking-details.yml"
      - "templates/category.yml"
      - "templates/event-details.yml"
      - "templates/organizer-table.yml" # Trigger only when DynamoDB template is changed
      - "templates/notification-details.yml" # added comment for checkin
      - "templates/city.yml" # added comment for checkin
      - "templates/college.yml" # Test
      - "templates/state.yml" # Test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the latest v3 version

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2 # Use v2 for latest support
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.ref == 'refs/heads/main' && 'us-west-2' || 'eu-west-1' }}

      - name: Deploy DynamoDB Table
        run: |
          aws cloudformation deploy --template-file templates/user-table.yml --stack-name yak-user-table-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/organizer-table.yml --stack-name yak-organizer-table-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/notification-details.yml --stack-name yak-notification-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/event-details.yml --stack-name yak-event-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/booking-details.yml --stack-name yak-booking-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/city.yml --stack-name yak-city-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/college.yml --stack-name yak-college-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/category.yml --stack-name yak-category-details-stack --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file templates/state.yml --stack-name yak-state-details-stack --capabilities CAPABILITY_NAMED_IAM
